/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRunnersRouteImport } from './routes/_app/runners'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app/repositories/index'
import { Route as AppRepositoriesRepositoryIdRouteImport } from './routes/_app/repositories/$repositoryId'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs/index'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs/$runId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunnersRoute = AppRunnersRouteImport.update({
  id: '/runners',
  path: '/runners',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRepositoryIdRoute =
  AppRepositoriesRepositoryIdRouteImport.update({
    id: '/repositories/$repositoryId',
    path: '/repositories/$repositoryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/runners': typeof AppRunnersRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/repositories/': typeof AppRepositoriesIndexRoute
  '/runs/': typeof AppRunsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/runners': typeof AppRunnersRoute
  '/': typeof AppIndexRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/runs': typeof AppRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/runners': typeof AppRunnersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
  '/_app/runs/': typeof AppRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/runners'
    | '/repositories/$repositoryId'
    | '/runs/$runId'
    | '/repositories/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/runners'
    | '/'
    | '/repositories/$repositoryId'
    | '/runs/$runId'
    | '/repositories'
    | '/runs'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/runners'
    | '/_app/'
    | '/_app/repositories/$repositoryId'
    | '/_app/runs/$runId'
    | '/_app/repositories/'
    | '/_app/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runners': {
      id: '/_app/runners'
      path: '/runners'
      fullPath: '/runners'
      preLoaderRoute: typeof AppRunnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$repositoryId': {
      id: '/_app/repositories/$repositoryId'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppRunnersRoute: typeof AppRunnersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRepositoriesRepositoryIdRoute: typeof AppRepositoriesRepositoryIdRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppRunnersRoute: AppRunnersRoute,
  AppIndexRoute: AppIndexRoute,
  AppRepositoriesRepositoryIdRoute: AppRepositoriesRepositoryIdRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
