/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFeaturesRouteImport } from './routes/_app/features'
import { Route as AppFeaturesIndexRouteImport } from './routes/_app/features/index'
import { Route as AppFeaturesNewRouteImport } from './routes/_app/features/new'
import { Route as AppRepositoriesIndexRouteImport } from './routes/_app/repositories/index'
import { Route as AppRepositoriesRepositoryIdRouteImport } from './routes/_app/repositories/$repositoryId'
import { Route as AppRunnersIndexRouteImport } from './routes/_app/runners/index'
import { Route as AppRunnersApproveRouteImport } from './routes/_app/runners/approve'
import { Route as AppRunsIndexRouteImport } from './routes/_app/runs/index'
import { Route as AppRunsRunIdRouteImport } from './routes/_app/runs/$runId'
import { Route as AppFeaturesFeatureIdIndexRouteImport } from './routes/_app/features/$featureId/index'
import { Route as AppFeaturesFeatureIdFilesContextFileIdRouteImport } from './routes/_app/features/$featureId/files/$contextFileId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesRoute = AppFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesIndexRoute = AppFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFeaturesRoute,
} as any)
const AppFeaturesNewRoute = AppFeaturesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppFeaturesRoute,
} as any)
const AppRepositoriesIndexRoute = AppRepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => AppRoute,
} as any)
const AppRepositoriesRepositoryIdRoute =
  AppRepositoriesRepositoryIdRouteImport.update({
    id: '/repositories/$repositoryId',
    path: '/repositories/$repositoryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppRunnersIndexRoute = AppRunnersIndexRouteImport.update({
  id: '/runners/',
  path: '/runners/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunnersApproveRoute = AppRunnersApproveRouteImport.update({
  id: '/runners/approve',
  path: '/runners/approve',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsIndexRoute = AppRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppFeaturesFeatureIdIndexRoute =
  AppFeaturesFeatureIdIndexRouteImport.update({
    id: '/$featureId/',
    path: '/$featureId/',
    getParentRoute: () => AppFeaturesRoute,
  } as any)
const AppFeaturesFeatureIdFilesContextFileIdRoute =
  AppFeaturesFeatureIdFilesContextFileIdRouteImport.update({
    id: '/$featureId/files/$contextFileId',
    path: '/$featureId/files/$contextFileId',
    getParentRoute: () => AppFeaturesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/get-started': typeof GetStartedRoute
  '/sign-in': typeof SignInRoute
  '/features': typeof AppFeaturesRouteWithChildren
  '/features/new': typeof AppFeaturesNewRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/runners/approve': typeof AppRunnersApproveRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/features/': typeof AppFeaturesIndexRoute
  '/repositories/': typeof AppRepositoriesIndexRoute
  '/runners/': typeof AppRunnersIndexRoute
  '/runs/': typeof AppRunsIndexRoute
  '/features/$featureId/': typeof AppFeaturesFeatureIdIndexRoute
  '/features/$featureId/files/$contextFileId': typeof AppFeaturesFeatureIdFilesContextFileIdRoute
}
export interface FileRoutesByTo {
  '/get-started': typeof GetStartedRoute
  '/sign-in': typeof SignInRoute
  '/': typeof AppIndexRoute
  '/features/new': typeof AppFeaturesNewRoute
  '/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/runners/approve': typeof AppRunnersApproveRoute
  '/runs/$runId': typeof AppRunsRunIdRoute
  '/features': typeof AppFeaturesIndexRoute
  '/repositories': typeof AppRepositoriesIndexRoute
  '/runners': typeof AppRunnersIndexRoute
  '/runs': typeof AppRunsIndexRoute
  '/features/$featureId': typeof AppFeaturesFeatureIdIndexRoute
  '/features/$featureId/files/$contextFileId': typeof AppFeaturesFeatureIdFilesContextFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/sign-in': typeof SignInRoute
  '/_app/features': typeof AppFeaturesRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/features/new': typeof AppFeaturesNewRoute
  '/_app/repositories/$repositoryId': typeof AppRepositoriesRepositoryIdRoute
  '/_app/runners/approve': typeof AppRunnersApproveRoute
  '/_app/runs/$runId': typeof AppRunsRunIdRoute
  '/_app/features/': typeof AppFeaturesIndexRoute
  '/_app/repositories/': typeof AppRepositoriesIndexRoute
  '/_app/runners/': typeof AppRunnersIndexRoute
  '/_app/runs/': typeof AppRunsIndexRoute
  '/_app/features/$featureId/': typeof AppFeaturesFeatureIdIndexRoute
  '/_app/features/$featureId/files/$contextFileId': typeof AppFeaturesFeatureIdFilesContextFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/sign-in'
    | '/features'
    | '/features/new'
    | '/repositories/$repositoryId'
    | '/runners/approve'
    | '/runs/$runId'
    | '/features/'
    | '/repositories/'
    | '/runners/'
    | '/runs/'
    | '/features/$featureId/'
    | '/features/$featureId/files/$contextFileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/get-started'
    | '/sign-in'
    | '/'
    | '/features/new'
    | '/repositories/$repositoryId'
    | '/runners/approve'
    | '/runs/$runId'
    | '/features'
    | '/repositories'
    | '/runners'
    | '/runs'
    | '/features/$featureId'
    | '/features/$featureId/files/$contextFileId'
  id:
    | '__root__'
    | '/_app'
    | '/get-started'
    | '/sign-in'
    | '/_app/features'
    | '/_app/'
    | '/_app/features/new'
    | '/_app/repositories/$repositoryId'
    | '/_app/runners/approve'
    | '/_app/runs/$runId'
    | '/_app/features/'
    | '/_app/repositories/'
    | '/_app/runners/'
    | '/_app/runs/'
    | '/_app/features/$featureId/'
    | '/_app/features/$featureId/files/$contextFileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features': {
      id: '/_app/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof AppFeaturesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features/': {
      id: '/_app/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof AppFeaturesIndexRouteImport
      parentRoute: typeof AppFeaturesRoute
    }
    '/_app/features/new': {
      id: '/_app/features/new'
      path: '/new'
      fullPath: '/features/new'
      preLoaderRoute: typeof AppFeaturesNewRouteImport
      parentRoute: typeof AppFeaturesRoute
    }
    '/_app/repositories/': {
      id: '/_app/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AppRepositoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repositories/$repositoryId': {
      id: '/_app/repositories/$repositoryId'
      path: '/repositories/$repositoryId'
      fullPath: '/repositories/$repositoryId'
      preLoaderRoute: typeof AppRepositoriesRepositoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runners/': {
      id: '/_app/runners/'
      path: '/runners'
      fullPath: '/runners/'
      preLoaderRoute: typeof AppRunnersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runners/approve': {
      id: '/_app/runners/approve'
      path: '/runners/approve'
      fullPath: '/runners/approve'
      preLoaderRoute: typeof AppRunnersApproveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/': {
      id: '/_app/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AppRunsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs/$runId': {
      id: '/_app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/features/$featureId/': {
      id: '/_app/features/$featureId/'
      path: '/$featureId'
      fullPath: '/features/$featureId/'
      preLoaderRoute: typeof AppFeaturesFeatureIdIndexRouteImport
      parentRoute: typeof AppFeaturesRoute
    }
    '/_app/features/$featureId/files/$contextFileId': {
      id: '/_app/features/$featureId/files/$contextFileId'
      path: '/$featureId/files/$contextFileId'
      fullPath: '/features/$featureId/files/$contextFileId'
      preLoaderRoute: typeof AppFeaturesFeatureIdFilesContextFileIdRouteImport
      parentRoute: typeof AppFeaturesRoute
    }
  }
}

interface AppFeaturesRouteChildren {
  AppFeaturesNewRoute: typeof AppFeaturesNewRoute
  AppFeaturesIndexRoute: typeof AppFeaturesIndexRoute
  AppFeaturesFeatureIdIndexRoute: typeof AppFeaturesFeatureIdIndexRoute
  AppFeaturesFeatureIdFilesContextFileIdRoute: typeof AppFeaturesFeatureIdFilesContextFileIdRoute
}

const AppFeaturesRouteChildren: AppFeaturesRouteChildren = {
  AppFeaturesNewRoute: AppFeaturesNewRoute,
  AppFeaturesIndexRoute: AppFeaturesIndexRoute,
  AppFeaturesFeatureIdIndexRoute: AppFeaturesFeatureIdIndexRoute,
  AppFeaturesFeatureIdFilesContextFileIdRoute:
    AppFeaturesFeatureIdFilesContextFileIdRoute,
}

const AppFeaturesRouteWithChildren = AppFeaturesRoute._addFileChildren(
  AppFeaturesRouteChildren,
)

interface AppRouteChildren {
  AppFeaturesRoute: typeof AppFeaturesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppRepositoriesRepositoryIdRoute: typeof AppRepositoriesRepositoryIdRoute
  AppRunnersApproveRoute: typeof AppRunnersApproveRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppRepositoriesIndexRoute: typeof AppRepositoriesIndexRoute
  AppRunnersIndexRoute: typeof AppRunnersIndexRoute
  AppRunsIndexRoute: typeof AppRunsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeaturesRoute: AppFeaturesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppRepositoriesRepositoryIdRoute: AppRepositoriesRepositoryIdRoute,
  AppRunnersApproveRoute: AppRunnersApproveRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppRepositoriesIndexRoute: AppRepositoriesIndexRoute,
  AppRunnersIndexRoute: AppRunnersIndexRoute,
  AppRunsIndexRoute: AppRunsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
