import { meGet } from './me.ts';
import {
  repositoryAdd,
  repositoryGet,
  repositoryList,
  repositoryListInstallable,
  repositoryRemove,
  repositorySetupRefresh,
  repositorySetupScan,
  repositorySetupStart,
  repositoryUpdate,
} from './repository.ts';
import { runCancel, runCreate, runGet, runList } from './run.ts';
import { runnerCreatePairingCode, runnerList, runnerPair, runnerRevoke } from './runner.ts';

export { MeGetOutput, UserRole } from './me.ts';
export { PageInput } from './pagination.ts';
export {
  AgentRole,
  DEFAULT_WORKFLOW_SETTINGS,
  GITHUB_FAILED_MESSAGE_MAX,
  GithubRepositoryId,
  INSTALLABLE_REPOSITORIES_MAX,
  InstallableRepository,
  InvalidSelectionData,
  RepositoryAddInput,
  RepositoryDetail,
  RepositoryListInstallableOutput,
  RepositorySummary,
  RepositoryUpdateInput,
  ReviewRounds,
  ReviewSettings,
  RoleSetting,
  RoleSettings,
  SetupStartInput,
  WorkflowSettings,
} from './repository.ts';
export {
  CatalogKind,
  DESCRIPTION_MAX,
  Orchestrator,
  Recommendation,
  RepositoryScan,
  SCAN_PATH_MAX,
  ScannedSkill,
  SelectionError,
  SETUP_BRANCH,
  SETUP_INPUTS_MAX,
  SETUP_JOB_MAX_BYTES,
  SetupSelection,
  SetupStatus,
  SkillFilePath,
  SkillLocation,
  SkillName,
  SKILLS_ROOT,
  SLOT_LINE_PATTERN,
} from './repository-setup.ts';
export {
  CommitSha,
  GitRef,
  Repository,
  Run,
  RunCancelReason,
  RunCreateInput,
  RunFailureReason,
  RunKind,
  RunStatus,
  RunSummary,
  RUN_PROMPT_MAX,
  TERMINAL_RUN_STATUSES,
} from './run.ts';
export {
  AGENT_NAME_MAX,
  AGENT_TEXT_MAX,
  FAILURE_MESSAGE_MAX,
  isTerminalRunEvent,
  RateLimitStatus,
  RUN_EVENTS_PATH,
  RunEvent,
  RunEventBody,
  RunEventType,
  runEventsPath,
  RunnerRunEventBody,
  SETUP_PUSHED_PATHS_MAX,
  SETUP_PUSHED_PATHS_MAX_BYTES,
  SKILL_NAME_MAX,
  SKILLS_MAX,
  STDERR_LINE_MAX,
  STDERR_TAIL_LINES,
  TERMINAL_RUN_EVENT_TYPES,
} from './run-event.ts';
export {
  CLAUDE_CODE_MIN_VERSION,
  CliStatus,
  PAIRING_CODE_PATTERN,
  Runner,
  RunnerPlatform,
  RunnerStatus,
} from './runner.ts';
export {
  MAX_ACTIVE_RUNS,
  MAX_EVENTS_MESSAGE_BYTES,
  MAX_EVENTS_PER_MESSAGE,
  MAX_SOCKET_MESSAGE_BYTES,
  jsonByteLength,
  RunJob,
  RunnerSocketClose,
  RunnerToServerMessage,
  ServerToRunnerMessage,
  SETUP_FILE_CONTENT_MAX,
  SETUP_FILES_MAX,
  SetupFile,
  SetupJob,
  TestJob,
} from './runner-protocol.ts';

export const contract = {
  me: { get: meGet },
  runner: {
    createPairingCode: runnerCreatePairingCode,
    pair: runnerPair,
    list: runnerList,
    revoke: runnerRevoke,
  },
  run: { create: runCreate, get: runGet, list: runList, cancel: runCancel },
  repository: {
    listInstallable: repositoryListInstallable,
    add: repositoryAdd,
    list: repositoryList,
    get: repositoryGet,
    update: repositoryUpdate,
    remove: repositoryRemove,
  },
  repositorySetup: {
    scan: repositorySetupScan,
    start: repositorySetupStart,
    refresh: repositorySetupRefresh,
  },
};
