import {
  instanceCompleteGithubApp,
  instanceGetStatus,
  instanceGithubAppManifest,
} from './instance.ts';
import { meGet } from './me.ts';
import {
  repositoryAdd,
  repositoryGet,
  repositoryList,
  repositoryListInstallable,
  repositoryRemove,
  repositorySetupRefresh,
  repositorySetupScan,
  repositorySetupStart,
  repositoryUpdate,
} from './repository.ts';
import { runCancel, runCreate, runGet, runList } from './run.ts';
import {
  runnerApproveLogin,
  runnerDenyLogin,
  runnerGetLogin,
  runnerList,
  runnerPollLogin,
  runnerRevoke,
  runnerStartLogin,
} from './runner.ts';

export { GITHUB_FAILED_MESSAGE_MAX } from './github-failed.ts';
export {
  GithubAppState,
  InstanceCompleteGithubAppInput,
  InstanceGithubAppManifestInput,
  InstanceGithubAppManifestOutput,
  InstanceStatus,
  SetupToken,
} from './instance.ts';
export { MeGetOutput, UserRole } from './me.ts';
export { PageInput } from './pagination.ts';
export {
  AgentRole,
  DEFAULT_WORKFLOW_SETTINGS,
  GithubRepositoryId,
  INSTALLABLE_REPOSITORIES_MAX,
  InstallableRepository,
  InvalidSelectionData,
  RepositoryAddInput,
  RepositoryDetail,
  RepositoryListInstallableOutput,
  RepositorySummary,
  RepositoryUpdateInput,
  ReviewRounds,
  ReviewSettings,
  RoleSetting,
  RoleSettings,
  SetupStartInput,
  WorkflowSettings,
} from './repository.ts';
export {
  CatalogKind,
  DESCRIPTION_MAX,
  INSTRUCTION_FILES_MAX,
  Orchestrator,
  ORCHESTRATOR_REFERENCES_MAX,
  Recommendation,
  RepositoryScan,
  SCAN_PATH_MAX,
  SCAN_SKILLS_MAX,
  ScannedSkill,
  SelectionError,
  SETUP_BRANCH,
  SETUP_INPUTS_MAX,
  SETUP_JOB_MAX_BYTES,
  SetupSelection,
  SetupStatus,
  SkillFilePath,
  SkillLocation,
  SkillName,
  SKILLS_ROOT,
  SLOT_LINE_PATTERN,
  UNMOVABLE_CONTENT_MAX,
} from './repository-setup.ts';
export {
  CommitSha,
  GitRef,
  Repository,
  Run,
  RunCancelReason,
  RunCreateInput,
  RunFailureReason,
  RunKind,
  RunStatus,
  RunSummary,
  RUN_PROMPT_MAX,
  TERMINAL_RUN_STATUSES,
} from './run.ts';
export {
  AGENT_NAME_MAX,
  AGENT_TEXT_MAX,
  FAILURE_MESSAGE_MAX,
  isTerminalRunEvent,
  RateLimitStatus,
  RUN_EVENTS_PATH,
  RunEvent,
  RunEventBody,
  RunEventType,
  runEventsPath,
  RunnerRunEventBody,
  SETUP_PUSHED_PATHS_MAX,
  SETUP_PUSHED_PATHS_MAX_BYTES,
  SKILL_NAME_MAX,
  SKILLS_MAX,
  STDERR_LINE_MAX,
  STDERR_TAIL_LINES,
  TERMINAL_RUN_EVENT_TYPES,
} from './run-event.ts';
export {
  CLAUDE_CODE_MIN_VERSION,
  CliStatus,
  Runner,
  RunnerLogin,
  RunnerLoginStatus,
  RunnerPlatform,
  RunnerPollLoginOutput,
  RunnerStartLoginOutput,
  RunnerStatus,
  RunnerUserCode,
} from './runner.ts';
export { RUNNER_LOGIN_MESSAGE_MAX, RunnerLoginEvent } from './runner-cli.ts';
export {
  MAX_ACTIVE_RUNS,
  MAX_EVENTS_MESSAGE_BYTES,
  MAX_EVENTS_PER_MESSAGE,
  MAX_SOCKET_MESSAGE_BYTES,
  RunJob,
  RunnerSocketClose,
  RunnerToServerMessage,
  ServerToRunnerMessage,
  SETUP_FILE_CONTENT_MAX,
  SETUP_FILES_MAX,
  SetupFile,
  SetupJob,
  TestJob,
} from './runner-protocol.ts';

export const contract = {
  instance: {
    getStatus: instanceGetStatus,
    githubAppManifest: instanceGithubAppManifest,
    completeGithubApp: instanceCompleteGithubApp,
  },
  me: { get: meGet },
  runner: {
    startLogin: runnerStartLogin,
    pollLogin: runnerPollLogin,
    getLogin: runnerGetLogin,
    approveLogin: runnerApproveLogin,
    denyLogin: runnerDenyLogin,
    list: runnerList,
    revoke: runnerRevoke,
  },
  run: { create: runCreate, get: runGet, list: runList, cancel: runCancel },
  repository: {
    listInstallable: repositoryListInstallable,
    add: repositoryAdd,
    list: repositoryList,
    get: repositoryGet,
    update: repositoryUpdate,
    remove: repositoryRemove,
  },
  repositorySetup: {
    scan: repositorySetupScan,
    start: repositorySetupStart,
    refresh: repositorySetupRefresh,
  },
};
